/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employees;

/**
 *
 * @author Lia
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Workers extends javax.swing.JFrame
{

    Connection connection;
    Statement statement;
    ResultSet resultSet;
    int currentRow = 0;

    /**
     * Creates new form Workers
     */
    public Workers()
    {
        initComponents();
        DoConnect();
    }

    public void DoConnect()
    {
        try
        {
            String host = "jdbc:derby://localhost:1527/Employees";
            String userName = "testing";
            String password = "testing";
            this.connection = DriverManager.getConnection(host, userName, password);
            this.statement = this.connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            this.resultSet = this.statement.executeQuery("SELECT * FROM Workers");
            this.resultSet.next();
            this.jTextFieldID.setText(Integer.toString(this.resultSet.getInt("ID")));
            this.jTextFieldFirstName.setText(this.resultSet.getString("First_Name"));
            this.jTextFieldLastName.setText(this.resultSet.getString("Last_Name"));
            this.jTextFieldJobTitle.setText(this.resultSet.getString("Job_Title"));
        } catch (SQLException err)
        {
            JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldJobTitle = new javax.swing.JTextField();
        jLabelJobTitle = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonFirst = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonLast = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonUpdateRecord = new javax.swing.JButton();
        jButtonDeleteRecord = new javax.swing.JButton();
        jButtonNewRecord = new javax.swing.JButton();
        jButtonSaveNewRecord = new javax.swing.JButton();
        jButtonCancelNewRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelJobTitle.setText("Job Title:");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelJobTitle)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldJobTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJobTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonFirst.setText("First");
        jButtonFirst.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonFirstActionPerformed(evt);
            }
        });

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonLast.setText("Last");
        jButtonLast.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLastActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("Previous");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonFirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLast)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonFirst)
                .addComponent(jButtonNext)
                .addComponent(jButtonLast)
                .addComponent(jButtonPrevious))
        );

        jButtonUpdateRecord.setText("Update Record");
        jButtonUpdateRecord.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonUpdateRecordActionPerformed(evt);
            }
        });

        jButtonDeleteRecord.setText("Delete Record");
        jButtonDeleteRecord.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDeleteRecordActionPerformed(evt);
            }
        });

        jButtonNewRecord.setText("New Record");
        jButtonNewRecord.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonNewRecordActionPerformed(evt);
            }
        });

        jButtonSaveNewRecord.setText("Save New Record");
        jButtonSaveNewRecord.setEnabled(false);
        jButtonSaveNewRecord.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSaveNewRecordActionPerformed(evt);
            }
        });

        jButtonCancelNewRecord.setText("Cancel New Record");
        jButtonCancelNewRecord.setEnabled(false);
        jButtonCancelNewRecord.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelNewRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButtonUpdateRecord)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteRecord)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonNewRecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jButtonSaveNewRecord)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelNewRecord)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdateRecord)
                    .addComponent(jButtonDeleteRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewRecord)
                    .addComponent(jButtonSaveNewRecord)
                    .addComponent(jButtonCancelNewRecord))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldIDActionPerformed
    {//GEN-HEADEREND:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonNextActionPerformed
    {//GEN-HEADEREND:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        try
        {
            if (resultSet.next())
            {
                this.jTextFieldID.setText(Integer.toString(this.resultSet.getInt("ID")));
                this.jTextFieldFirstName.setText(this.resultSet.getString("First_Name"));
                this.jTextFieldLastName.setText(this.resultSet.getString("Last_Name"));
                this.jTextFieldJobTitle.setText(this.resultSet.getString("Job_Title"));

            } else
            {
                resultSet.previous();
                JOptionPane.showMessageDialog(Workers.this, "End of File");
            }
        } catch (SQLException err)
        {
            JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonPreviousActionPerformed
    {//GEN-HEADEREND:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
        try
        {
            if (resultSet.previous())
            {
                this.jTextFieldID.setText(Integer.toString(this.resultSet.getInt("ID")));
                this.jTextFieldFirstName.setText(this.resultSet.getString("First_Name"));
                this.jTextFieldLastName.setText(this.resultSet.getString("Last_Name"));
                this.jTextFieldJobTitle.setText(this.resultSet.getString("Job_Title"));

            } else
            {
                resultSet.next();
                JOptionPane.showMessageDialog(Workers.this, "Beginning of File");
            }
        } catch (SQLException err)
        {
            JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonLastActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonLastActionPerformed
    {//GEN-HEADEREND:event_jButtonLastActionPerformed
        // TODO add your handling code here:
        try
        {
            resultSet.last();
            this.jTextFieldID.setText(Integer.toString(this.resultSet.getInt("ID")));
            this.jTextFieldFirstName.setText(this.resultSet.getString("First_Name"));
            this.jTextFieldLastName.setText(this.resultSet.getString("Last_Name"));
            this.jTextFieldJobTitle.setText(this.resultSet.getString("Job_Title"));
        } catch (SQLException err)
        {
            JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }
    }//GEN-LAST:event_jButtonLastActionPerformed

    private void jButtonFirstActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonFirstActionPerformed
    {//GEN-HEADEREND:event_jButtonFirstActionPerformed
        // TODO add your handling code here:
        try
        {
            resultSet.first();
            this.jTextFieldID.setText(Integer.toString(this.resultSet.getInt("ID")));
            this.jTextFieldFirstName.setText(this.resultSet.getString("First_Name"));
            this.jTextFieldLastName.setText(this.resultSet.getString("Last_Name"));
            this.jTextFieldJobTitle.setText(this.resultSet.getString("Job_Title"));
        } catch (SQLException err)
        {
            JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }
    }//GEN-LAST:event_jButtonFirstActionPerformed

    private void jButtonUpdateRecordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonUpdateRecordActionPerformed
    {//GEN-HEADEREND:event_jButtonUpdateRecordActionPerformed
        // TODO add your handling code here:
        String first = this.jTextFieldFirstName.getText();
        String last = this.jTextFieldLastName.getText();
        String job = this.jTextFieldJobTitle.getText();
        String ID = this.jTextFieldID.getText();
        try
        {
            int newID = Integer.parseInt(ID);
            this.resultSet.updateInt("ID", newID);
            this.resultSet.updateString("First_Name", first);
            this.resultSet.updateString("last_Name", last);
            this.resultSet.updateString("Job_Title", job);
            this.resultSet.updateRow();
            JOptionPane.showMessageDialog(Workers.this, "Updated");
        } catch (SQLException err)
        {
             JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }

    }//GEN-LAST:event_jButtonUpdateRecordActionPerformed

    private void jButtonDeleteRecordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDeleteRecordActionPerformed
    {//GEN-HEADEREND:event_jButtonDeleteRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteRecordActionPerformed

    private void jButtonNewRecordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonNewRecordActionPerformed
    {//GEN-HEADEREND:event_jButtonNewRecordActionPerformed
        try
        {
            // TODO add your handling code here:
            this.jButtonFirst.setEnabled(false);
            this.jButtonPrevious.setEnabled(false);
            this.jButtonNext.setEnabled(false);
            this.jButtonLast.setEnabled(false);
            this.jButtonUpdateRecord.setEnabled(false);
            this.jButtonDeleteRecord.setEnabled(false);
            this.jButtonNewRecord.setEnabled(false);
            this.jButtonSaveNewRecord.setEnabled(true);
            this.jButtonCancelNewRecord.setEnabled(true);
            this.jTextFieldFirstName.setText("");
            this.jTextFieldID.setText("");
            this.jTextFieldJobTitle.setText("");
            this.jTextFieldLastName.setText("");
            this.currentRow = this.resultSet.getRow();
        } catch (SQLException ex)
        {
            Logger.getLogger(Workers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonNewRecordActionPerformed

    private void jButtonCancelNewRecordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelNewRecordActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelNewRecordActionPerformed
        // TODO add your handling code here:
        this.jButtonFirst.setEnabled(true);
        this.jButtonPrevious.setEnabled(true);
        this.jButtonNext.setEnabled(true);
        this.jButtonLast.setEnabled(true);
        this.jButtonUpdateRecord.setEnabled(true);
        this.jButtonDeleteRecord.setEnabled(true);
        this.jButtonNewRecord.setEnabled(true);
        this.jButtonSaveNewRecord.setEnabled(false);
        this.jButtonCancelNewRecord.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelNewRecordActionPerformed

    private void jButtonSaveNewRecordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSaveNewRecordActionPerformed
    {//GEN-HEADEREND:event_jButtonSaveNewRecordActionPerformed
        // TODO add your handling code here:
        this.jButtonFirst.setEnabled(true);
        this.jButtonPrevious.setEnabled(true);
        this.jButtonNext.setEnabled(true);
        this.jButtonLast.setEnabled(true);
        this.jButtonUpdateRecord.setEnabled(true);
        this.jButtonDeleteRecord.setEnabled(true);
        this.jButtonNewRecord.setEnabled(true);
        this.jButtonSaveNewRecord.setEnabled(false);
        this.jButtonCancelNewRecord.setEnabled(false);
    }//GEN-LAST:event_jButtonSaveNewRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Workers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelNewRecord;
    private javax.swing.JButton jButtonDeleteRecord;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonNewRecord;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonSaveNewRecord;
    private javax.swing.JButton jButtonUpdateRecord;
    private javax.swing.JLabel jLabelJobTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldJobTitle;
    private javax.swing.JTextField jTextFieldLastName;
    // End of variables declaration//GEN-END:variables
}
